import type { GrammarQuestion, VocabularyQuestion } from '@/lib/types'

export const grammarQuestions: GrammarQuestion[] = [
  {
    id: 1,
    sentence: "By the time we arrived at the station, the train _____ already.",
    options: ["has left", "had left", "was leaving"],
    correctIndex: 1,
  },
  {
    id: 2,
    sentence: "If I _____ more time, I would have finished the project.",
    options: ["had had", "would have", "have had"],
    correctIndex: 0,
  },
  {
    id: 3,
    sentence: "She suggested that he _____ the doctor immediately.",
    options: ["sees", "saw", "see"],
    correctIndex: 2,
  },
  {
    id: 4,
    sentence: "The report _____ by the committee before the deadline.",
    options: ["was reviewed", "has reviewed", "reviewed"],
    correctIndex: 0,
  },
  {
    id: 5,
    sentence: "Not only _____ late, but she also forgot her presentation.",
    options: ["she was", "was she", "she had been"],
    correctIndex: 1,
  },
  {
    id: 6,
    sentence: "He _____ in London for five years when he decided to move to Paris.",
    options: ["lived", "has lived", "had been living"],
    correctIndex: 2,
  },
  {
    id: 7,
    sentence: "The new policy _____ by all employees starting next month.",
    options: ["must be followed", "must follow", "must have followed"],
    correctIndex: 0,
  },
  {
    id: 8,
    sentence: "Despite _____ the instructions carefully, she made several errors.",
    options: ["to follow", "followed", "following"],
    correctIndex: 2,
  },
  {
    id: 9,
    sentence: "I wish I _____ to the conference last week.",
    options: ["went", "had gone", "would go"],
    correctIndex: 1,
  },
  {
    id: 10,
    sentence: "The manager asked the team _____ the project by Friday.",
    options: ["completing", "to complete", "complete"],
    correctIndex: 1,
  },
  {
    id: 11,
    sentence: "Rarely _____ such an impressive performance at this venue.",
    options: ["we have seen", "have we seen", "we saw"],
    correctIndex: 1,
  },
  {
    id: 12,
    sentence: "It is essential that every participant _____ the safety guidelines.",
    options: ["reads", "read", "reading"],
    correctIndex: 1,
  },
  {
    id: 13,
    sentence: "The project _____ unless we receive additional funding.",
    options: ["will be cancelled", "would be cancelled", "is cancelled"],
    correctIndex: 0,
  },
  {
    id: 14,
    sentence: "Having _____ all the evidence, the jury reached a verdict.",
    options: ["considered", "considering", "to consider"],
    correctIndex: 0,
  },
  {
    id: 15,
    sentence: "The more you practise, _____ you will become.",
    options: ["the fluent", "fluenter", "the more fluent"],
    correctIndex: 2,
  },
  {
    id: 16,
    sentence: "She denied _____ the confidential documents.",
    options: ["to take", "taking", "take"],
    correctIndex: 1,
  },
  {
    id: 17,
    sentence: "By next year, the construction company _____ the new bridge.",
    options: ["will complete", "will have completed", "completes"],
    correctIndex: 1,
  },
  {
    id: 18,
    sentence: "The book _____ be returned to the library by Friday at the latest.",
    options: ["should", "ought", "is supposed"],
    correctIndex: 0,
  },
  {
    id: 19,
    sentence: "I'd rather you _____ your phone during the meeting.",
    options: ["don't use", "didn't use", "not use"],
    correctIndex: 1,
  },
  {
    id: 20,
    sentence: "The phenomenon _____ by scientists only recently.",
    options: ["has been explained", "was being explained", "is explained"],
    correctIndex: 0,
  },
  {
    id: 21,
    sentence: "_____ he been more careful, the accident would never have happened.",
    options: ["If", "Had", "Should"],
    correctIndex: 1,
  },
  {
    id: 22,
    sentence: "She spent three hours _____ the quarterly financial report.",
    options: ["to prepare", "prepared", "preparing"],
    correctIndex: 2,
  },
  {
    id: 23,
    sentence: "It is high time we _____ a decision about the budget cuts.",
    options: ["make", "made", "will make"],
    correctIndex: 1,
  },
  {
    id: 24,
    sentence: "No sooner _____ his speech than the audience burst into applause.",
    options: ["he finished", "did he finish", "has he finished"],
    correctIndex: 1,
  },
  {
    id: 25,
    sentence: "The CEO, _____ has been with the company for twenty years, announced her retirement.",
    options: ["who", "whom", "which"],
    correctIndex: 0,
  },
]

export const vocabularyQuestions: VocabularyQuestion[] = [
  {
    id: 1,
    type: 'definition',
    question: "Which word means 'to officially end or cancel a law or agreement'?",
    options: ["Ratify", "Rescind", "Reinforce"],
    correctIndex: 1,
  },
  {
    id: 2,
    type: 'synonym',
    question: "Choose the word closest in meaning to 'METICULOUS'.",
    options: ["Careless", "Thorough", "Rapid"],
    correctIndex: 1,
  },
  {
    id: 3,
    type: 'context',
    question: "The company's decision to expand overseas was seen as _____ given the current economic uncertainty.",
    options: ["prudent", "audacious", "trivial"],
    correctIndex: 1,
  },
  {
    id: 4,
    type: 'definition',
    question: "Which word describes 'a short story that teaches a moral lesson'?",
    options: ["Anecdote", "Parable", "Chronicle"],
    correctIndex: 1,
  },
  {
    id: 5,
    type: 'synonym',
    question: "Choose the word closest in meaning to 'EXACERBATE'.",
    options: ["Alleviate", "Worsen", "Ignore"],
    correctIndex: 1,
  },
  {
    id: 6,
    type: 'context',
    question: "The new manager tried to _____ the tension between the two departments by organising team-building activities.",
    options: ["escalate", "mitigate", "perpetuate"],
    correctIndex: 1,
  },
  {
    id: 7,
    type: 'definition',
    question: "What does 'PRAGMATIC' mean?",
    options: ["Idealistic", "Practical", "Pessimistic"],
    correctIndex: 1,
  },
  {
    id: 8,
    type: 'synonym',
    question: "Which word is closest in meaning to 'CONCUR'?",
    options: ["Disagree", "Coincide", "Contradict"],
    correctIndex: 1,
  },
  {
    id: 9,
    type: 'context',
    question: "The scientist's findings were _____ by several independent research teams, confirming their validity.",
    options: ["disputed", "corroborated", "dismissed"],
    correctIndex: 1,
  },
  {
    id: 10,
    type: 'definition',
    question: "Which word means 'unwilling to spend money'?",
    options: ["Generous", "Frugal", "Extravagant"],
    correctIndex: 1,
  },
  {
    id: 11,
    type: 'synonym',
    question: "Choose the word closest in meaning to 'ELOQUENT'.",
    options: ["Inarticulate", "Articulate", "Blunt"],
    correctIndex: 1,
  },
  {
    id: 12,
    type: 'context',
    question: "Her argument was so _____ that even her opponents had to admit she made valid points.",
    options: ["flimsy", "compelling", "confusing"],
    correctIndex: 1,
  },
  {
    id: 13,
    type: 'definition',
    question: "What does 'AMBIGUOUS' describe?",
    options: ["Clear and precise", "Open to multiple interpretations", "Completely false"],
    correctIndex: 1,
  },
  {
    id: 14,
    type: 'synonym',
    question: "Which word is closest in meaning to 'INSTIGATE'?",
    options: ["Prevent", "Investigate", "Initiate"],
    correctIndex: 2,
  },
  {
    id: 15,
    type: 'context',
    question: "The documentary aimed to _____ awareness about the dangers of plastic pollution.",
    options: ["diminish", "raise", "ignore"],
    correctIndex: 1,
  },
  {
    id: 16,
    type: 'definition',
    question: "Which word means 'to formally approve or confirm a treaty or agreement'?",
    options: ["Revoke", "Ratify", "Reject"],
    correctIndex: 1,
  },
  {
    id: 17,
    type: 'synonym',
    question: "Choose the word closest in meaning to 'INEVITABLE'.",
    options: ["Optional", "Unavoidable", "Surprising"],
    correctIndex: 1,
  },
  {
    id: 18,
    type: 'context',
    question: "The politician's speech was deliberately _____, avoiding any firm commitments.",
    options: ["evasive", "transparent", "forthright"],
    correctIndex: 0,
  },
  {
    id: 19,
    type: 'definition',
    question: "What does 'EMPIRICAL' mean?",
    options: ["Based on theory", "Based on observation and evidence", "Based on tradition"],
    correctIndex: 1,
  },
  {
    id: 20,
    type: 'synonym',
    question: "Which word is closest in meaning to 'VOLATILE'?",
    options: ["Stable", "Unpredictable", "Calm"],
    correctIndex: 1,
  },
  {
    id: 21,
    type: 'context',
    question: "She was known for her _____ approach to problem-solving, always finding creative solutions.",
    options: ["conventional", "innovative", "rigid"],
    correctIndex: 1,
  },
  {
    id: 22,
    type: 'definition',
    question: "Which word describes 'showing a willingness to take surprisingly bold risks'?",
    options: ["Timid", "Audacious", "Cautious"],
    correctIndex: 1,
  },
  {
    id: 23,
    type: 'synonym',
    question: "Choose the word closest in meaning to 'SUPERFICIAL'.",
    options: ["Deep", "Thorough", "Shallow"],
    correctIndex: 2,
  },
  {
    id: 24,
    type: 'context',
    question: "The committee decided to _____ the deadline, giving candidates two extra weeks to submit.",
    options: ["advance", "extend", "cancel"],
    correctIndex: 1,
  },
  {
    id: 25,
    type: 'definition',
    question: "What does 'REPERCUSSION' mean?",
    options: ["An unintended consequence", "A direct result", "A positive outcome"],
    correctIndex: 0,
  },
]
